### ISSUE TITLE
[enhancement] Teaching materials button

### ISSUE THREAD

**Issue by boutreet** [leaphy-robotics/leaphy-webbased-svelte#141]
Add a button with a link to relevant "teaching materials" (video's, documentation) in the workspace view. Maybe per block for sensors/actuators that have a video, or just with one button in the menu bar that sends you to the docs depending on the robot type.

**Comment by rmoesbergen** [comment]
There's a "helpurl" setting for each block in Blockly. Not sure where this ends up, but it might be what we need.
