### ISSUE TITLE
[enhancement] Block definition overwrites previous definition warning

### ISSUE THREAD

**Issue by JeftadeGraaf** [leaphy-robotics/leaphy-webbased-svelte#25]
When we are working in a workspace and decide to start a new one. All the blocks are redefined, causing a lot of errors in the console.log.

![Image](https://github.com/leaphy-robotics/leaphy-webbased/assets/91546552/9e5148c3-da77-46ff-b8c0-88615f31dac6)

**Comment by koen1711** [comment]
@rmoesbergen I think this is already fixed in Svelte?

**Comment by koen1711** [comment]
Just confirmed, it is.
![image](https://github.com/leaphy-robotics/leaphy-webbased-svelte/assets/98043234/1988459f-4c9d-4325-ae5f-84d199304877)
