### ISSUE TITLE
[parity] save as save to micropython robot

### ISSUE THREAD

**Issue by koen1711** [leaphy-robotics/leaphy-webbased-svelte#43]
### How can we better our software?

![image](https://github.com/leaphy-robotics/leaphy-webbased-svelte/assets/98043234/30633eb3-bbd4-4f19-a155-d76799d40396)
In micropython you should be able to save a file here to the robot itself, not to your own computer.

### What area is your feature improving?

Robot Support, Micropython Environment

**Comment by koen1711** [comment]
@sverben Close?

**Comment by sverben** [comment]
Feel free to close it if you don't see the feature as necessary
