### ISSUE TITLE
[enhancement] add an "You have a save" indication

### ISSUE THREAD

**Issue by koen1711** [leaphy-robotics/leaphy-webbased-svelte#47]
### How can we better our software?

Could be a popup or something on top of the robot tiles or something, preferably not a popup because you already get bombarded with those.

### What area is your feature improving?

User Interface

**Comment by rmoesbergen** [comment]
A little icon on the robot tile would be nice

**Comment by rmoesbergen** [comment]
We need to re-think this because combined with the 'always save your workspace', this doesn't make sense. After some time you end up with a save icon on every robot forever.

**Comment by rmoesbergen** [comment]
With the new submenu this makes even less sense... lets' close this.
